"""initial migration with sentiment analysis fields

Revision ID: a7b4ae11ab7b
Revises: 
Create Date: 2025-09-25 04:40:30.829723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b4ae11ab7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Confianza de la predicción de sentimiento (0-1)'))
    op.add_column('reviews', sa.Column('sentiment_label', sa.Text(), nullable=True, comment='Etiqueta de sentimiento: positive o negative'))
    op.create_index('idx_reviews_sentiment', 'reviews', ['sentiment_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_sentiment', table_name='reviews')
    op.drop_column('reviews', 'sentiment_label')
    op.drop_column('reviews', 'sentiment_score')
    # ### end Alembic commands ###
